version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: bdd_container
    environment:
      - POSTGRES_USER=hugo
      - POSTGRES_PASSWORD=hugo
      - POSTGRES_DB=api_rest_tp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_bridge

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - postgres_bridge

volumes:
  postgres_data:

networks:
  postgres_bridge:
    driver: bridge
